version: "3"
services:
  mongodb:
    container_name: BUSINESS_NAME_mongodb-prod
    image: mongo
    logging:
      driver: none
    ports:
      - "27017:27017"
    # volumes:
    #   - BUSINESS_NAME-dbdata:/data/db
  mongo-seed:
    container_name: BUSINESS_NAME_mongo-seed-prod
    image: shivangp502/BUSINESS_NAME_mongo-seed:latest
    build: ./mongo-seed/
    depends_on:
      - mongodb
    restart: on-failure
  backend:
    container_name: BUSINESS_NAME_backend-prod
    image: shivangp502/BUSINESS_NAME_backend:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile-prod
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  frontend:
    container_name: BUSINESS_NAME_frontend-prod
    image: shivangp502/BUSINESS_NAME_frontend:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile-prod
    ports:
      - "8080:80"
    depends_on:
      - backend
# volumes: BUSINESS_NAME-dbdata:
